### PR TITLE
Add bitbucket-compatible template

### PR DESCRIPTION
**Pull request by cerkiewny**
Api doc generates useless <p> tags inside description, I am removing them manually in the template.
Not sure what is best strategy to provide it as default template or some other example.

### CODE REVIEW

**Comment by rigwild** [comment]
Hi, HTML tags in Markdown is valid and should not be visible when rendered.

apidoc add these (as you mentionned), but I am not confident with removing it as apidoc also accepts HTML tags as input in comments (e.g. `@apiDescription example <p>paragraph</p>.`) and could lead to difficult to debug result for apidoc-markdown users.

Thanks for the contribution though. To install your version locally you can do:

```
yarn build
yarn link

apidoc-markdown -v
```

**Comment by cerkiewny** [comment]
I know they should be, however bitbucket doesn't parse them properly. I have made the other PR in which I am putting the template as bitbucket template, it would definitely help out folks who use bitbucket as their system, the links as "<a>" as well as "<p>" tags don't seem to work there. Not sure if you want it in your repo or not.

**Comment by rigwild** [comment]
I will add a bitbucket-specific template as you suggested then I guess. I have to edit something in the core lib beforehand. Thanks

**Comment by rigwild** [comment]
Thank you for the contribution! I added the `bitbucket` template to the repo and the hability to path the name of the chosen template like so:

 - Template name (`default` or `bitbucket`)
 - Template path `./path/to/template.md`

**Pull request merged**
