### PR TITLE
Respect project order settings

### PR DESCRIPTION
**Pull request by vanekj**
Hi!

Thank you for this module, it suits our project very well, but we do miss the possibility of an order of the items so I made a bit of update.

Please check out the changes and let me know in case of updates 🙂

### CODE REVIEW

**Comment by rigwild** [comment]
Thanks for your contribution to the project!
I will look into it soon, I am pretty busy this week.
Have a nice day.

**Comment by rigwild** [comment]
Hey @vanekj 
I cleaned your code.

It had an error there:
https://github.com/rigwild/apidoc-markdown/blob/661f1d6b9d7fd2cf8c9b21638194f458ba96194f/lib/index.js#L51-L60

You forgot to remove duplicate entries. I fixed it by adding a new feature: select only the entry having the latest version number using [semver](https://www.npmjs.com/package/semver) (thanks @minigugus for the help).

Let me know what you think about these changes.
Could you provide an example for your order configuration so I can describe the feature in the readme ?

Have a nice day!

**Comment by vanekj** [comment]
Hi @rigwild, sorry for that bug!

I have updated the repository examples folder to "groups" by the type that could be generated (basic, multi, ordered). Let me know if you are OK with that change so I can revert the changes if not :) I have also updated examples section in README.

I have also added editorconfig file as my default configuration is different.

Regards!

**Comment by rigwild** [comment]
Thank you for your contribution. I added you to the `contributors` in [`package.json`](./package.json) 😊

**Comment by vanekj** [comment]
Thank you! Glad I helped

**Pull request merged**
